import { Providers } from "@/components/providers";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "100 Days Of MVP",
  description: "Generated by 100 Days Of MVP",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
