import { Providers } from "@/components/providers";
import "./globals.css";
import type { Metadata } from "next";
import { Sora } from 'next/font/google';

export const metadata: Metadata = {
  title: "100 Days Of MVP",
  description: "Generated by 100 Days Of MVP",
};

const sora = Sora({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
