import { Providers } from "@/components/providers";
import "./globals.css";
import type { Metadata } from "next";
import { Sora } from 'next/font/google';

export const metadata: Metadata = {
  title: "100 Days Of MVP",
  description: "Generated by 100 Days Of MVP",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <head><link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Sora:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet" /> </head>
      <body style={{ fontFamily: "'Sora', sans-serif" }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
